interface Node {
  id: ID!
  name: String!
}

type Person implements Node {
  id: ID!
  name: String!
  groups: [Group!]!
}

type Group implements Node {
  id: ID!
  name: String!
  members: [Node!]!
}

type Query {
  node(id: ID!): Node
}
